<?php

namespace TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;
use TicketBundle\Entity\Customer;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    /**
     * @param Customer $customer
     */
    public function save(Customer $customer)
    {
        $this->_em->persist($customer);
        $this->_em->flush();
    }
}
