<?php

namespace TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;
use TicketBundle\Entity\CustomerTicket;

/**
 * CustomerTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerTicketRepository extends EntityRepository
{
    /**
     * @param CustomerTicket $customerTicket
     */
    public function save(CustomerTicket $customerTicket)
    {
        $this->_em->persist($customerTicket);
        $this->_em->flush();
    }
}
