<?php

namespace TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;
use TicketBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @param Event $event
     */
    public function save(Event $event)
    {
        $this->_em->persist($event);
        $this->_em->flush();
    }
}
