<?php

namespace TicketBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTicketRepository extends EntityRepository
{
}
